#!/bin/bash
set -e
source /opt/mailserver/mailserver.conf

echo "========================================"
echo " Roundcube Configuration"
echo "========================================"

if [ "$EUID" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi

# Read the DB password generated by 01-install.sh
if [ -f /opt/mailserver-install.tmp ]; then
    source /opt/mailserver-install.tmp
else
    echo "ERROR: /opt/mailserver-install.tmp not found."
    echo "Run 01-install.sh first."
    exit 1
fi

echo
echo "[1/6] Generating secure keys..."
# des_key: used to encrypt session cookies. Must be unique per deployment.
# If you lose this key, all existing sessions are invalidated.
DES_KEY=$(pwgen -s 24 1)

echo
echo "[2/6] Configuring Roundcube..."
cat > /etc/roundcube/config.inc.php <<EOF
<?php
\$config = [];

// Database — uses the password generated during install
include('/etc/roundcube/debian-db-roundcube.php');

// IMAP: connect to Dovecot on port 143 with STARTTLS
// In production replace with ssl://localhost:993 after cert setup
\$config['imap_host'] = 'tls://mail.namit.com:143';

// SMTP: connect to Postfix submission port 587 with STARTTLS
// Port 587 requires auth + TLS — correct for outbound mail
\$config['smtp_host'] = 'mail.namit.com:587';
\$config['smtp_port'] = 587;

// Use the logged-in user's credentials for SMTP submission
// Postfix will verify these against Dovecot auth → LDAP
\$config['smtp_user'] = '%u';
\$config['smtp_pass'] = '%p';

// Session security
\$config['des_key']      = '${DES_KEY}';
\$config['product_name'] = 'Mail';

// Plugins
\$config['plugins'] = [
    'archive',
    'zipdownload',
    'managesieve',   // lets users create mail filter rules (Sieve)
    'markasjunk',    // adds Junk/Not-Junk buttons → triggers imapsieve → trains rspamd
];

\$config['skin']             = 'elastic';
\$config['enable_spellcheck']= false;
\$config['language']         = 'en_US';

// ManageSieve — connects to Dovecot's ManageSieve service (port 4190)
// Users can create rules like "if subject contains SPAM → move to Junk"
\$config['managesieve_port']   = 4190;
\$config['managesieve_host']   = 'localhost';
\$config['managesieve_usetls'] = false;

// Mark as junk — moves message to Junk folder
// imapsieve in Dovecot catches this and calls rspamc learn_spam
\$config['markasjunk_move_spam'] = true;
\$config['markasjunk_spam_folder']= 'Junk';

// Show quota in UI
\$config['quota_zero_as_unlimited'] = false;
EOF

echo
echo "[3/6] Initialising Roundcube database schema..."
if mysql -u root -e "SELECT COUNT(*) FROM information_schema.tables \
    WHERE table_schema='roundcube';" 2>/dev/null | grep -q "^0$"; then
    mysql roundcube < /usr/share/roundcube/SQL/mysql.initial.sql
    echo "Database schema imported."
else
    echo "Database already initialised, skipping."
fi

echo
echo "[4/6] Configuring Apache virtual host..."
cat > /etc/apache2/sites-available/roundcube.conf <<EOF
<VirtualHost *:80>

    ServerName mail.namit.com

    DocumentRoot /usr/share/roundcube

    <Directory /usr/share/roundcube>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/roundcube-error.log
    CustomLog ${APACHE_LOG_DIR}/roundcube-access.log combined

</VirtualHost>

# HTTPS vhost — uncomment after running certbot
# <VirtualHost *:443>
#     ServerName $MAILHOST
#     DocumentRoot /usr/share/roundcube
#     SSLEngine on
#     SSLCertificateFile    /etc/letsencrypt/live/$MAILHOST/fullchain.pem
#     SSLCertificateKeyFile /etc/letsencrypt/live/$MAILHOST/privkey.pem
#     <Directory /usr/share/roundcube>
#         Options -Indexes +FollowSymLinks
#         AllowOverride All
#         Require all granted
#     </Directory>
# </VirtualHost>
EOF

echo
echo "[5/6] Enabling Apache modules and site..."
a2enmod rewrite ssl headers > /dev/null 2>&1
a2ensite roundcube.conf > /dev/null 2>&1
a2dissite 000-default.conf > /dev/null 2>&1 || true
apache2ctl configtest

echo
echo "[6/6] Restarting Apache..."
systemctl restart apache2
systemctl enable apache2

# Clean up temp file
rm -f /opt/mailserver-install.tmp

echo
echo "========================================"
echo " Roundcube Configuration Complete"
echo "========================================"
echo
echo " Roundcube URL : http://$MAILHOST"
echo " SMTP          : tls://localhost:587 (submission)"
echo " IMAP          : tls://localhost:143 (STARTTLS)"
echo " ManageSieve   : localhost:4190"
echo " Plugins       : managesieve, markasjunk, archive, zipdownload"
echo
echo " To enable HTTPS run:"
echo "   certbot --apache -d $MAILHOST"
